const {Schema, model} = require('mongoose');

const patientSchema = new Schema(
    {
      Vorname: {
        type: String,
        required: [true, 'Vorname ist ein Pflichtfeld'],   
      },
      Nachname: {
        type: String,
        required: [true, 'Nachname ist ein Pflichtfeld'],   
      },
      Geburtsdatum: {
        type: String,
        required: [true, 'Geburtsdatum ist ein Pflichtfeld'],
      },
      assessment1: {
        Adresse: String,
        Telefonnummer: String,
        Email: String,
        Krankenkasse: String,
        Hausarzt: String,
        Geschlecht: String,
        Herkunft: String,
        Muttersprache: String,
        SchulischeBildung: String,
        BeruflicheBildung: String,
        Beruf: String,
        weitereAngabenBeruf: Array,
        Familienstand: Array,
        Wohnsituation: Array,
        PersonenImHaushalt: String,
        WeitereAnmerkungenZurWohnsituation: String,
        aktuellGeraucht: String,
        jemalsGeraucht: String,
        AnzahlZigaretten: String,
        AnzahlTabakprodukte: String,
        AnzahlJahreRauchen: String,
        Beeintraechtigungen: Array,
        mobil: Array,
        UnterstuetzungMedizinischerVersorgung: Array,
        KontakAktivitaet: String,
        Hobbies: String,
        MedizinischeDiagnose: String,
        weitereDiagnosen: Array,
        vergangeneDiagnosen: String,
        PsychischeGesundheit: Array,
        GesundheitszustandDerFamilie: Array,
        WeitereAnmerkungenZumGesundheitszustandDerFamilie: String,
        Schwangerschaft: String,
        Stillzeit: String,
        UploadAssessment1: Array,
      },
      Recall: Array,
      anzahlRecall: Number,
      assessment2: {
        UploadErnahrungsprotokoll: Array,
        weitereGetraenke: String,
        AnzahlMahlzeitenRecall: String,
        MahlzeitenNormalerweise: String,
        MahlzeitenWeggelassen: Array,
        MahlzeitenZusaetzlich: Array,
        weitereAnmerkungenRecall: String,
        Vorlieben:String,
        Abneigungen: String,
        EigenstaendigeDiaet: Array,
        MahlzeitenAusserHaus: Array,
        DiaetischeKostform: Array,
        EnteraleErnaehrung: Array,
        Medikamente: Array,
        UploadAssessment2: Array,
      },
      bilanzierung:{
        Getraenke : String,
        Gemuese: String,
        Obst: String,
        Getreideprodukte: String,
        Milch: String,
        Fleisch: String,
        Fisch: String,
        Ei: String,
        Fette: String,
        Suessigkeiten: String,
        PikanteSnacks: String,
        Energie: String,
        Wasser: String,
        Eiweiss: String,
        Kohlenhydrate: String,
        Zucker: String,
        Ballaststoffe: String,
        Gesamtfett: String,
        GesaettigteFettsaeuren: String,
        EinfachUngesaettigte: String,
        MehrfachUngesaettigte: String,
        Cholesterin: String,
        CounterVitamine: Number,
        CounterMineralstoffe: Number,
      },
      Vitamine: Array,
      Mineralstoffe: Array,
      assessment3: {
        PlantMahlzeiten: Array,
        BereitetMahlzeiten: Array,
        weitereAnmerkungenMahlzeiten: String,
        Lebensmitteleinkauf: Array,
        Selbstversorgen: Array,
        EinfachheitMahlzeitZuzubereiten: Array,
        InformationErnaehrung: Array,
        weitereAnmerkungenInformationsquellen: String,
        OrientierungErnaehrung: String,
        WichtigkeitDerEmpfehlung: String,
        ErnaehrungsgewohnheitenVeraendern: Array,
        PhysicalActivityLevel: String,
        WeitereAnmerkungenAktivitaet: String,
        WhoLaune: Number,
        WhoRuhig: Number,
        WhoAktiv: Number,
        WhoAusgeruht: Number,
        WhoInteressieren: Number,
        WhoWert: Number,
        WhoProzent: Number,
        WhoAuswertung: String,
        UploadLebensqualitaet: Array,
        UploadAssessment3: Array,
      },
      wichtigkeit: {
        WichtigkeitDerFrische: String,
        WichtigkeitDesGeschmacks: String,
        WichtigkeitDerGesundheit: String,
        WichtigkeitEinesGeringenPreises: String,
        WichtigkeitDerRegionalitaet: String,
        WichtigkeitDerSaisonalitaet: String,
        CounterAndere: Number,
      },
      WichtigkeitAndere: Array,
      assessment4: { 
        Koerpergroesse: String,
        Koerpergewicht: String,
        Bmi: String,
        Taillenumfang: String,
        Hautfaltendicke: String,
        FettfreieMasse: String,
        Fettmasse:String,
        Ruheenergieumsatz: String,
        ChemieMetabolischeParameter: String,
        Vitalzeichen: String,
        WeitereMessungen: String,
        Schlucken: Array,
        Erbrechen: Array,
        Mundgesundheit: Array,
        ProblemeNahrungsaufnahme: String,
        AppetitBeeintraechtigung: String,
        WeitereKoerperlicheBefunde: String,
        UploadAssessment4: Array,
      },
      Diagnosestellung: Array,
      PASR: Array,
      Counter: Number,
      Error:Array,
      ErrorList: Array,
      Priorisierung: Array,
      UebergeordetesZiel: Array,
      Verlaufsziel: Array,
      planung: {
        Leitlinien: String,
        CounterUebergeordetesZiel: Number,
        CounterVerlaufsziel: Number,
        Ernaehrungsempfehlung: String,
        Interventionsform: Array,
        WeitereAnmerkungenInterventionform: String,
        ZeitraumIntervention: String,
        FrequenzInterventionen: String,
        PlanungEinzelberatung: Array,
        PlanungGruppenschulung: Array,
        PlanungEinkaufstraining: Array,
        PlanungLehrkueche: Array,
        PlanungAndereInterventionsform: Array,
        WeitereBerufsgruppen: Array,
        Angehoerige: String,
        WeitereAnmerkungenInterventionNochmal: String,
        Monitoring: Array,
        JoinMonitoring: Array,
      },
      UmsetzungEinzelberatung: Array,
      UmsetzungGruppenschulung: Array,
      UmsetzungEinkaufstraining: Array,
      UmsetzungLehrkueche: Array,
      UmsetzungAndereInterventionsform: Array,
      Zusatznahrung: String,
      EntwicklungZusatznahrung: Array,
      SonstigesUmsetung: String,        
      EntwicklungMonitoring: Array,
      evaluation: {
        EvaluationEntwicklungMonitoring: Array,
        ZielerreichungUebergeordetesZiel: Array,
        BegruendungZielerreichungUebergeordetesZiel: Array,
        ZielerreichungVerlaufsziel: Array,
        BegruendungZielerreichungVerlaufsziel: Array,
        EvaluationUebergeordetesZiel: Array,
        EvaluationVerlaufsziel: Array,
        EvaluationWeitersVorgehen: String,
      },
    },
    {timestamps:true},
);

module.exports = model ('patienten', patientSchema);